apiVersion: v1
kind: Service
metadata:
  name: laravel
  annotations:
    cloud.google.com/backend-config: '{"default": "allow-cdn"}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: laravel
  type: LoadBalancer
