apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-ethereum-demo-scan
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: go-ethereum-demo-scan
            image: myapp
            command: ["./scan"]
            imagePullPolicy: Always
          restartPolicy: OnFailure